title: B-Tails
description: Create a secure, privacy-focused bootable USB and encrypted drive with B-Tails guide
theme: just-the-docs
color_scheme: dark
# remote_theme: pmarsceill/just-the-docs
search_enabled: true
markdown: kramdown

mermaid:
  # Version of mermaid library. Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: 9.4.3
  # Put any additional configuration, such as setting the theme, in _includes/mermaid_config.js
  # See also docs/ui-components/code
  # path: "/assets/js/mermaid.min.js"

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

url: https://dutu.github.io/b-tails

aux_links:
  Issues / Knowledge Base: https://github.com/dutu/b-tails/issues
  Contribute! Source on GitHub: https://github.com/dutu/b-tails/
