title: B-Tails
description: Your secure computer & encrypted USB memory drive anywhere
theme: just-the-docs
color_scheme: dark
# remote_theme: pmarsceill/just-the-docs
search_enabled: true
markdown: kramdown

# To disable support for mermaid diagrams (https://mermaid.js.org),
# comment out the `mermaid` and `version` keys below
# By default, consuming the theme as a gem leaves mermaid disabled; it is opt-in
mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.3.0"
  # Put any additional configuration, such as setting the theme, in _includes/mermaid_config.js
  # See also docs/ui-components/code

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red


url: https://dutu.github.io/b-tails

aux_links:
  Issues / Knowledge Base: https://github.com/dutu/b-tails/issues
  Contribute! Source on GitHub: https://github.com/dutu/b-tails/
